<a href="https://colab.research.google.com/github/eduardiazcode/Jupyter-Notebook/blob/main/mi_primer_proyecto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Mi primer Proyecto con GoogLe Colab**

In [ ]:
import pandas as pd

In [ ]:
# Leer datos desde archivo CSV
csv_path = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
# Guarga el archivo csv en la variable csv_path
df=pd.read_csv(csv_path,sep=",",header=None)
# df es data frame = es como una tabla de datos lo mas comun es que se use df
# csv_path = indicamos de donde debe leer el archivos
# sep"," = le decimos que la informacion esta separado por comas
# header=None = estamos diciendo que los datos no tienen encabezados
df.head()
# que muestre las primeras 5 filas del dataframe

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
# Nombre de los atributos
# Crear una lista con los encabezados que tendras las columnas header (los encabezados)
headers = ["age", "workclass","fnlwgt","education","education-num", "marital-status","occupation",
         "relationship","race","sex", "capital-gain","capital-loss","hours-per-week","native-country","makes"]
df.columns = headers
# asigna esa lista a las columnas del dataframe
df.head(100)
# que muestre las 100 primeras filas

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,makes
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,29,Local-gov,115585,Some-college,10,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,50,United-States,<=50K
96,48,Self-emp-not-inc,191277,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1902,60,United-States,>50K
97,37,Private,202683,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States,>50K
98,48,Private,171095,Assoc-acdm,12,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,England,<=50K
99,32,Federal-gov,249409,HS-grad,9,Never-married,Other-service,Own-child,Black,Male,0,0,40,United-States,<=50K

In [ ]:
#La función dtypes genera una tabla con el tipo de dato de cada columna
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
makes             object
dtype: object

In [ ]:
# Consultado el tipo de dato de un columna especifica (educacion)
df['education'].dtype

dtype('O')

In [ ]:
# Consultado el tipo de dato de un columna especifica (edad)
df['age'].dtype

dtype('int64')

In [ ]:
# Consultado el tipo de dato de un columna especifica (sexo)
df['sex'].dtype

dtype('O')